# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kmgr < Formula
  desc "Description courte de ta CLI"
  homepage "https://github.com/UnPoilTefal/kmgr"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/UnPoilTefal/kmgr/releases/download/v0.2.0/kmgr_0.2.0_darwin_amd64.tar.gz"
      sha256 "20b0237beb5c5fb6de1c18d85f413d446f8d77624bb89c73ce64347dc322fe6c"

      define_method(:install) do
        bin.install "kmgr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/UnPoilTefal/kmgr/releases/download/v0.2.0/kmgr_0.2.0_darwin_arm64.tar.gz"
      sha256 "3f938e80ccae152905dc6905965247836f36fd4ecfd78688b22d8e8b688ff249"

      define_method(:install) do
        bin.install "kmgr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/UnPoilTefal/kmgr/releases/download/v0.2.0/kmgr_0.2.0_linux_amd64.tar.gz"
      sha256 "b60b3f8c9992acdc9f03197c61e44fdca9a7ae377c8002f338763c4b9a3bbdb1"
      define_method(:install) do
        bin.install "kmgr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/UnPoilTefal/kmgr/releases/download/v0.2.0/kmgr_0.2.0_linux_arm64.tar.gz"
      sha256 "3600c32b48cf88595cbb52f052bd9e37c350451b8d732bd93bf64e59f1e36848"
      define_method(:install) do
        bin.install "kmgr"
      end
    end
  end

  test do
    system "#{bin}/kmgr --version"
  end
end
