# This file was generated by GoReleaser. DO NOT EDIT.
cask "kmgr" do
  version "0.4.3"

  on_macos do
    on_arm do
      sha256 "f63d00b3414366ff2622a8ffb21a9bc7c16380bc486c977732751513dbed99e5"
      url "https://github.com/UnPoilTefal/kmgr/releases/download/v#{version}/kmgr_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7d46fe883c2856cfcef93d2c492e68f9078e728339ce3884f5c2c6f20f7fadf5"
      url "https://github.com/UnPoilTefal/kmgr/releases/download/v#{version}/kmgr_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f6eaeb9e5f7ccb415a154f547ebef9bd8b633f7137de9a1ca14bb74cffbfc87b"
      url "https://github.com/UnPoilTefal/kmgr/releases/download/v#{version}/kmgr_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "fc6a95737b19aeae21b132ca5cee80efc481bd1618f4c294f4907d32b18dafbd"
      url "https://github.com/UnPoilTefal/kmgr/releases/download/v#{version}/kmgr_#{version}_linux_amd64.tar.gz"
    end
  end

  name "kmgr"
  desc "Kubeconfig manager — normalize, merge and switch kubeconfigs with a strict naming convention"
  homepage "https://github.com/UnPoilTefal/kmgr"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kmgr"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kmgr"]
    end
  end

  # No zap stanza required
end
