# This file was generated by GoReleaser. DO NOT EDIT.
cask "kmgr" do
  version "0.4.2"

  on_macos do
    on_arm do
      sha256 "924ff9cc6569415b76053d49a506c63e4084fc711668a763e1409d29b2e9a2d0"
      url "https://github.com/UnPoilTefal/kmgr/releases/download/v#{version}/kmgr_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7244afc1cac8dd3d4d7d880a7ac8f9d1207ca958eec15c4264c575c2cdbdc5b1"
      url "https://github.com/UnPoilTefal/kmgr/releases/download/v#{version}/kmgr_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a8c19bb2bdeddcf72dcf817668ca24d6dbbf67b7f12318d27ad8da9e763d6456"
      url "https://github.com/UnPoilTefal/kmgr/releases/download/v#{version}/kmgr_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3de662dd91898c9e59c67400b5eae7bc4d15aff24a155d41ea1d6aa8881ba333"
      url "https://github.com/UnPoilTefal/kmgr/releases/download/v#{version}/kmgr_#{version}_linux_amd64.tar.gz"
    end
  end

  name "kmgr"
  desc "Kubeconfig manager — normalize, merge and switch kubeconfigs with a strict naming convention"
  homepage "https://github.com/UnPoilTefal/kmgr"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kmgr"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kmgr"]
    end
  end

  # No zap stanza required
end
