# This file was generated by GoReleaser. DO NOT EDIT.
cask "memory-kit" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "25798ef8aa755b3248b57b46f6d95b28b7233cfe3d7342deb431215ee9076116"
      url "https://github.com/UnPoilTefal/memory-kit/releases/download/v#{version}/memory-kit_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3ab5717fe4dedf56aac17dca279f539712656c7b6416d6e95bfd186aa5d2a80a"
      url "https://github.com/UnPoilTefal/memory-kit/releases/download/v#{version}/memory-kit_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8e685b41b087c0a42854569e070a5c1f218759587988f5bf50d07b033d8c94f4"
      url "https://github.com/UnPoilTefal/memory-kit/releases/download/v#{version}/memory-kit_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2f77d66ce8ddee8e2bf02c089bad859be0937d105727b340b7098fe98956ea2f"
      url "https://github.com/UnPoilTefal/memory-kit/releases/download/v#{version}/memory-kit_#{version}_linux_amd64.tar.gz"
    end
  end

  name "memory-kit"
  desc "Outillage d'un corpus de memoire agent : lint structurel, preuves rejouees, porte de readiness"
  homepage "https://github.com/UnPoilTefal/memory-kit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "memctl"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/memctl"]
    end
  end

  # No zap stanza required
end
