# This file was generated by GoReleaser. DO NOT EDIT.
cask "perimeter" do
  version "0.6.0"

  on_macos do
    on_arm do
      sha256 "1932652ac23d4ded9982b0573ec770601db9fe2913b6ccf10194d4c2161a1a51"
      url "https://github.com/UnPoilTefal/perimeter/releases/download/v#{version}/perimeter_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1dcdff7ca7208f81481a00a03bde720d43b8fd8132588472844ecf7e7a4f015b"
      url "https://github.com/UnPoilTefal/perimeter/releases/download/v#{version}/perimeter_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6cc8c715ebf5f2891023c9f44a29b8ab107d102e8944d8edbe3d9353999173bc"
      url "https://github.com/UnPoilTefal/perimeter/releases/download/v#{version}/perimeter_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1d020ad30746bd1db555f4bb533e793f74c02bf27c62dba8909776737e0001dd"
      url "https://github.com/UnPoilTefal/perimeter/releases/download/v#{version}/perimeter_#{version}_linux_amd64.tar.gz"
    end
  end

  name "perimeter"
  desc "Outillage d'un corpus de memoire agent : lint structurel, preuves rejouees, porte de readiness"
  homepage "https://github.com/UnPoilTefal/perimeter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "perctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/perctl"]
    end
  end

  # No zap stanza required
end
