# This file was generated by GoReleaser. DO NOT EDIT.
cask "perimeter" do
  version "0.9.0"

  on_macos do
    on_arm do
      sha256 "3401f1d5ec6c1dc532d886ace3733274d3896d04ba8319aea46f286e77d4fcd7"
      url "https://github.com/UnPoilTefal/perimeter/releases/download/v#{version}/perimeter_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b2d55c2004a8bbfb968152d40cb70a1b4ba03a3a2c54cd11c55c1bad8bb47086"
      url "https://github.com/UnPoilTefal/perimeter/releases/download/v#{version}/perimeter_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "55a9c847a2847fae54de7e9f5f2d58b1f2f25840f28bc52b7d3b38248966fccc"
      url "https://github.com/UnPoilTefal/perimeter/releases/download/v#{version}/perimeter_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9c275cd0568f18bc99d4cc51fa5fcf7bb028fb6c9857139377d90ef2c2eefb88"
      url "https://github.com/UnPoilTefal/perimeter/releases/download/v#{version}/perimeter_#{version}_linux_amd64.tar.gz"
    end
  end

  name "perimeter"
  desc "Outillage d'un corpus de memoire agent : lint structurel, preuves rejouees, porte de readiness"
  homepage "https://github.com/UnPoilTefal/perimeter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "perctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/perctl"]
    end
  end

  # No zap stanza required
end
