# This file was generated by GoReleaser. DO NOT EDIT.
cask "perimeter" do
  version "0.10.0"

  on_macos do
    on_arm do
      sha256 "f2074fac7442dbce2b9f7c62e21ae776d2c5610bcd42b9e598b1627636fab7a8"
      url "https://github.com/UnPoilTefal/perimeter/releases/download/v#{version}/perimeter_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d82866ae557d2e3b0e408a8072326b5012757ebd095affed9b8f722ed0928e8b"
      url "https://github.com/UnPoilTefal/perimeter/releases/download/v#{version}/perimeter_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6324a189b86de5ffb6be3a97ba8a56348157246007db155dea657c04bed3bd4d"
      url "https://github.com/UnPoilTefal/perimeter/releases/download/v#{version}/perimeter_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "38e3f14639396b71005fc441b7ed426a41050297f7b83c832b8b74b346a9214f"
      url "https://github.com/UnPoilTefal/perimeter/releases/download/v#{version}/perimeter_#{version}_linux_amd64.tar.gz"
    end
  end

  name "perimeter"
  desc "Outillage d'un corpus de memoire agent : lint structurel, preuves rejouees, porte de readiness"
  homepage "https://github.com/UnPoilTefal/perimeter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "perctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/perctl"]
    end
  end

  # No zap stanza required
end
